/** @type {import('tailwindcss').Config} */
// Tokens de diseño extraídos de cubalink_professional/DESIGN.md y los tailwind.config
// de las páginas generadas por Google Stitch. Se conservan EXACTAMENTE los valores originales.
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Design tokens (Material 3 - CubaLink)
        'surface': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#43474f',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'outline': '#737780',
        'outline-variant': '#c3c6d1',
        'surface-tint': '#3a5f94',
        'primary': '#001e40',
        'on-primary': '#ffffff',
        'primary-container': '#003366',
        'on-primary-container': '#799dd6',
        'inverse-primary': '#a7c8ff',
        'secondary': '#735c00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed65b',
        'on-secondary-container': '#745c00',
        'tertiary': '#001e42',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#003369',
        'on-tertiary-container': '#689def',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#a7c8ff',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#1f477b',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#574500',
        'tertiary-fixed': '#d6e3ff',
        'tertiary-fixed-dim': '#a9c7ff',
        'on-tertiary-fixed': '#001b3d',
        'on-tertiary-fixed-variant': '#00468b',
        'background': '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
        // Brand accents usados en las páginas
        'brand-gold': '#D4AF37',
        'brand-blue-deep': '#003366',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '48px',
        'gutter': '24px',
        'unit': '8px',
        'margin-mobile': '16px',
        'container-max': '1280px',
      },
      fontFamily: {
        'label-sm': ['Inter'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'display-lg': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg': ['Inter'],
        'title-md': ['Inter'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
